hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect_service:
    path: /connect/service/{service}
    defaults:  { _controller: HWIOAuthBundle:Connect:connectService }

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

facebook_connect:
    path: /connect/facebook

twitter_login:
    path: /login/check-twitter

twitter_connect:
    path: /connect/twitter

google_login:
    path: /login/check-google

google_connect:
    path: /connect/google
