hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connexion

hwi_oauth_connect_service:
    path: /connexion/service/{service}
    defaults:  { _controller: HWIOAuthBundle:Connect:connectService }

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connexion

facebook_login:
    path: /connexion/validation-facebook

facebook_connect:
    path: /connexion/facebook

twitter_login:
    path: /connexion/validation-twitter

twitter_connect:
    path: /connexion/twitter

google_login:
    path: /connexion/validation-google

google_connect:
    path: /connexion/google
