<?php

namespace AppBundle\Repository;

/**
 * TranslationPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationPageRepository extends \Doctrine\ORM\EntityRepository
{
}
