<?php

namespace AppBundle\Repository;

/**
 * TranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordingRepository extends \Doctrine\ORM\EntityRepository
{
}
