parameters:
    fos_comment.manager.comment.default.class: FOS2CommentBundle\Entity\CommentManager

services:
#    fos_comment.example:
#        class: FOSCommentBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
