easy_admin:
    site_name: '%site_name%'
    entities:
        User:
            class: UserBundle\Entity\User
            list:
                fields: ['username', 'firstname', 'lastname', 'email', 'roles', 'lastLogin', 'enabled', 'locked']
            edit:
                fields: ['enabled', 'username', 'firstname', 'lastname', 'email', 'roles', 'lastLogin', 'locked']
            show:
                fields: ['enabled', 'username', 'firstname', 'lastname', 'email', 'roles', 'lastLogin', 'locked']
            new:
                fields: ['enabled', 'username', 'firstname', 'lastname', 'plainPassword', 'email', 'roles', 'lastLogin']
        Category:
            class: ProductBundle\Entity\Category
            list:
                fields: ['id', 'name', 'parent', 'slug', 'path']
            new:
                fields: ['name', 'parent']
            edit:
                fields: ['name', 'parent']
        Currency:
            class: ProductBundle\Entity\Currency
        Status:
            class: ProductBundle\Entity\Status
        Address:
            class: LocationBundle\Entity\Address
        Delivery:
            class: OrderBundle\Entity\Delivery
        Product:
            class: ProductBundle\Entity\Product
            edit:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'category' }
                    - { property: 'price' }
                    - { property: 'currency' }
                    - { property: 'status' }
                    - { property: 'user' }
                    - { property: 'address', type: 'easyadmin_autocomplete' }
                    - { property: 'images', type_options: { by_reference: false} }
                    - { property: 'allow_offer', type: 'checkbox' }
                    - { property: 'weight' }
                    - { property: 'width' }
                    - { property: 'length' }
                    - { property: 'height' }
            show:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'category' }
                    - { property: 'price' }
                    - { property: 'currency' }
                    - { property: 'status' }
                    - { property: 'user' }
                    - { property: 'address' }
                    - { property: 'images' }
                    - { property: 'allow_offer' }
                    - { property: 'weight' }
                    - { property: 'width' }
                    - { property: 'length' }
                    - { property: 'height' }
            new:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'category' }
                    - { property: 'price' }
                    - { property: 'currency' }
                    - { property: 'status' }
                    - { property: 'user' }
                    - { property: 'address', type: 'easyadmin_autocomplete' }
                    - { property: 'images', type_options: { by_reference: false} }
                    - { property: 'allow_offer', type: 'checkbox' }
                    - { property: 'weight' }
                    - { property: 'width' }
                    - { property: 'length' }
                    - { property: 'height' }
            list:
                fields:
                    ['id', 'name', 'user', 'createdAt', 'category', 'price', 'currency', 'status', 'address']
        Image:
            class: ProductBundle\Entity\Image
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'imagePath', type: 'image', base_path: /images/products }
            show:
                fields:
                    - { property: 'imagePath', type: 'image', base_path: /images/products }
            new:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
            edit:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'product'
        Referential:
            class: ProductBundle\Entity\Referential
        ReferentialValue:
            class: ProductBundle\Entity\ReferentialValue
            new:
                fields:
                    - { property: 'value' }
                    - { property: 'referentials', type_options: { by_reference: false} }
            edit:
                fields:
                    - { property: 'value' }
                    - { property: 'referentials', type_options: { by_reference: false} }
        Attribute:
            class: ProductBundle\Entity\Attribute
        AttributeValue:
            class: ProductBundle\Entity\AttributeValue
        Collection:
            class: ProductBundle\Entity\Collection
            new:
                fields:
                    - { property: 'name' }
                    - { property: 'description' }
                    - { property: 'categories' }
                    - { property: 'products' }
                    - { property: 'image', type_options: { by_reference: false} }
        CollectionImage:
            class: ProductBundle\Entity\CollectionImage
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'imagePath', type: 'image', base_path: /images/collections }
            show:
                fields:
                    - { property: 'imagePath', type: 'image', base_path: /images/collections }
            new:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
            edit:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - 'collection'
        City:
          class: LocationBundle\Entity\City
        DeliveryMode:
          class: OrderBundle\Entity\DeliveryMode
          edit:
              fields:
                  - { property: 'name' }
                  - { property: 'code' }
          new:
              fields:
                  - { property: 'name' }
                  - { property: 'code' }
          list:
              fields:
                  - { property: 'name' }
                  - { property: 'code' }
        Order:
            class: OrderBundle\Entity\Order
            list:
                title: "Commandes"
                actions: ['-new', '-delete', '-edit', 'show']
                fields:
                    - { property: 'id' }
                    - { property: 'product', label: "Produit" }
                    - { property: 'amount', label: "Montant total" }
                    - { property: 'productAmount', label: "Prix du produit" }
                    - { property: 'deliveryAmount', label: "Frais de port" }
                    - { property: 'delivery.deliveryMode.name', label: "Livraison" }
                    - { property: 'status', label: "Statut" }
                    - { property: 'createdAt', label: "Date de création" }
            show:
                actions: ['-delete', '-edit']
                fields:
                    - { property: 'id' }
                    - { property: 'product', label: "Produit" }
                    - { property: 'amount', label: "Montant total" }
                    - { property: 'productAmount', label: "Prix du produit" }
                    - { property: 'deliveryAmount', label: "Frais de port" }
                    - { property: 'delivery.deliveryMode.name', label: "Livraison" }
                    - { property: 'status', label: "Statut" }
                    - { property: 'user', label: "Acheteur" }
                    - { property: 'product.user', label: "Vendeur" }
                    - { property: 'DeliveryAddress', label: "Adresse de livraison" }
                    - { property: 'BillingAddress', label: "Adresse de facturation" }
                    - { property: 'createdAt', label: "Date de création" }
                    - { property: 'updatedAt', label: "Date de mise à jour" }
                    - { property: 'mangopayPreauthorizationId' }
                    - { property: 'mangopayPayinId' }
                    - { property: 'mangopayPayinDate' }
                    - { property: 'mangopayRefundId' }
                    - { property: 'mangopayTransferId' }
                    - { property: 'mangopayRefundDate' }


    design:
        menu:
            - { label: 'Site web', route: 'homepage' }
            - { label: 'Ecommerce' }
            - { label: 'Modération', route: 'admin_moderate' }
            - Order
            - Product
            - Image
            - AttributeValue
            - { label: 'Utilisateur' }
            - User
            - { label: 'Messages', route: 'admin_messages' }
            - { label: 'Référentiel' }
            - Referential
            - ReferentialValue
            - { label: 'Configuration' }
            - Category
            - Attribute
            - Status
            - Currency
            - { label: 'Collection' }
            - Collection
            - CollectionImage