imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: ['cron']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: [!event, !security, !cron]
        console:
            type:   console
            channels: [!event, !doctrine, !cron]
        login:
            type: stream
            path: "%kernel.logs_dir%/auth_%kernel.environment%.log"
            channels: security
        cron:
            type: stream
            path: "%kernel.logs_dir%/cron_%kernel.environment%.log"
            channels: cron
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

assetic:
    use_controller: false
    debug: true