imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: UserBundle\Form\RegistrationType
        confirmation:
            enabled: true
            from_email:
                address:        noreply@noname.com
                sender_name:    NoName Inscription


    profile:
        form:
            type: UserBundle\Form\ProfileFormType
    from_email:
        address:        noreply@noname.com
        sender_name:    NoName :)

hwi_oauth:
    connect:
        account_connector: oauth.user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            twitter: twitter_id
            google: google_id
    resource_owners:
        facebook:
            type: facebook
            client_id: %oauth.facebook.id%
            client_secret: %oauth.facebook.secret%
            infos_url: "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,locale,location,picture.type(square)"
            scope:  "public_profile,email"
            paths:
                email: email
                firstname: first_name
                lastname: last_name
                gender: gender
                profilepicture: picture.data.url
                locale: locale
            options:
                display: popup
        twitter:
            type: twitter
            client_id: %oauth.twitter.id%
            client_secret: %oauth.twitter.secret%
            scope:               ""
            paths:
                nickname: screen_name
        google:
            type: google
            client_id: %oauth.google.id%
            client_secret: %oauth.google.secret%
            scope: "email profile"
            options:
                display: popup
easy_admin:
    site_name: 'NoName'
    entities:
        User:
            class: UserBundle\Entity\User
            list:
                fields: ['username', 'firstname', 'lastname', 'email', 'roles', 'lastLogin', 'enabled']
            edit:
                fields: ['enabled', 'username', 'firstname', 'lastname', 'email', 'roles', 'lastLogin']
            new:
                fields: ['enabled', 'username', 'firstname', 'lastname', 'plainPassword', 'email', 'roles', 'lastLogin']
        Category:
            class: CategoryBundle\Entity\Category
            list:
                fields: ['id', 'name', 'parent', 'slug']
            new:
                fields: ['name', 'parent']
            edit:
                fields: ['name', 'parent', 'slug']