imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin.yml }
    - { resource: elasticsearch.yml }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ProductBundle/Resources/config/services.yml" }
    - { resource: "@ImageBundle/Resources/config/services.yml" }
    - { resource: "@LocationBundle/Resources/config/services.yml" }
    - { resource: "@MessageBundle/Resources/config/services.yml" }
    - { resource: "@CartBundle/Resources/config/services.yml" }
    - { resource: "@OrderBundle/Resources/config/services.yml" }
    - { resource: "@DepositBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    mangopay:
        client_id: %mangopay.client_id%
        client_password: %mangopay.client_password%
        base_url: %mangopay.base_url%
        fee_rate: %mangopay.fee_rate%
        fixed_fee: %mangopay.fixed_fee%
        max_output: %mangopay.max_output%
        max_input: %mangopay.max_input%
        temporary_folder: "%kernel.root_dir%/../var/mangopay"
    mailer_sender:
        from_email: %mailer_sender_email%
        from_name: %mailer_sender_name%

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - bootstrap_3_layout.html.twig
        - AppBundle:Form:form_layout.html.twig
    globals:
        pagerfanta_opts:
            dots_message:     ‘ … ‘


# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        result_cache_driver: memcached
        query_cache_driver: memcached
        second_level_cache:
            enabled: true
            log_enabled: true
            region_cache_driver: memcached
            regions:
                category_cache:
                    cache_driver:  memcached
                    lifetime:   3600
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_cache:
    aliases:
        cache: my_cache

    providers:
        my_cache:
            type: memcached
            namespace: my_cache_ns
            aliases:
                - app_cache

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type: UserBundle\Form\RegistrationType
        confirmation:
            enabled: true
            template: UserBundle:email:registration_confirmation.email.twig
            from_email:
                address:        %mailer_sender_email%
                sender_name:    %mailer_sender_name%
    resetting:
        email:
            template: UserBundle:email:password_resetting.email.twig
    profile:
        form:
            type: UserBundle\Form\ProfileFormType
    from_email:
        address:        %mailer_sender_email%
        sender_name:    %mailer_sender_name%


fos_message:
    db_driver: orm
    thread_class: MessageBundle\Entity\Thread
    message_class: MessageBundle\Entity\Message

hwi_oauth:
    connect:
        account_connector: oauth.user_provider
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            facebook: facebook_id
            twitter: twitter_id
            google: google_id
    resource_owners:
        facebook:
            type: facebook
            client_id: %oauth.facebook.id%
            client_secret: %oauth.facebook.secret%
            infos_url: "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,locale,location,picture.type(square)"
            scope:  "public_profile,email"
            paths:
                email: email
                firstname: first_name
                lastname: last_name
                gender: gender
                profilepicture: picture.data.url
                locale: locale
            options:
                display: popup
        twitter:
            type: twitter
            client_id: %oauth.twitter.id%
            client_secret: %oauth.twitter.secret%
            scope:               ""
            paths:
                nickname: screen_name
        google:
            type: google
            client_id: %oauth.google.id%
            client_secret: %oauth.google.secret%
            scope: "email profile"
            options:
                display: popup

lexik_currency:
    currencies:
        default: EUR              # [required] the default currency
        managed: [EUR, USD, ...]  # [required] all currencies used in your app
    currency_class: ProductBundle\Entity\Currency

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         /images/products
            upload_destination: %kernel.root_dir%/../web/images/products
            namer:              vich_uploader.namer_uniqid
            directory_namer:    directory_namer.product
        collection_images:
            uri_prefix:         /images/collections
            upload_destination: "%kernel.root_dir%/../web/images/collections"
            namer:              vich_uploader.namer_uniqid
            directory_namer:    directory_namer.product

fos_js_routing:
    routes_to_expose: [ 'fos_user_security_login', 'product_favorite', 'product_cart', 'ajax_search', 'search', 'ajax_search_attribute_filters', 'ajax_search_city', 'ajax_product_action', 'deposit_subcategories', 'upload_picture' ]
