admin2:
    resource: "@Admin2Bundle/Controller/"
    type:     annotation
    prefix:   /ad2

comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /

deposit:
    resource: "@DepositBundle/Controller/"
    type:     annotation
    prefix:   /

image:
    resource: "@ImageBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

location:
    resource: "@LocationBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@UserBundle/Resources/config/routing/fos_user/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

user_oauth:
    resource: "@UserBundle/Resources/config/routing/oauth.yml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
