blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

admin2:
    resource: "@Admin2Bundle/Controller/"
    type:     annotation
    prefix:   /admin

comment:
    resource: "@CommentBundle/Controller/"
    type:     annotation
    prefix:   /

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

cart:
    resource: "@CartBundle/Controller/"
    type:     annotation
    prefix:   /

deposit:
    resource: "@DepositBundle/Controller/"
    type:     annotation
    prefix:   /

image:
    resource: "@ImageBundle/Controller/"
    type:     annotation
    prefix:   /

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

location:
    resource: "@LocationBundle/Controller/"
    type:     annotation
    prefix:   /
fos_user:
    resource: "@UserBundle/Resources/config/routing/fos_user/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation

user_oauth:
    resource: "@UserBundle/Resources/config/routing/oauth.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /froalaeditor