# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.htmlform_login:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path:            /profil
                target_path_parameter:          _target_path
                use_referer:                    false
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path: fos_user_security_logout
            anonymous:    true

            oauth:
                resource_owners:
                    facebook:    "/connexion/validation-facebook"
                    twitter:    "/connexion/validation-twitter"
                    google:    "/connexion/validation-google"
                login_path:    fos_user_security_login
                failure_path:    fos_user_security_login
                oauth_user_provider:
                    service: oauth.user_provider
                default_target_path: /profil

    access_control:
        - { path: ^/connexion, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reinitialisation, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compte/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
