# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    oauth.user_provider:
        class: %oauth.user_provider.class%
        arguments: ['@fos_user.user_manager', { facebook: facebook_id, twitter: twitter_id, google: google_id }, '@doctrine.orm.entity_manager', '@service_container']

    app.form.registration:
        class: UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profil:
        class: UserBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_form_profil }

    directory_namer.product:
        class: ProductBundle\Service\DirectoryNamer

    product_bundle.listener.uploaded_file_listener:
        class: ProductBundle\EventListener\UploadedFileListener
        tags:
            - { name: kernel.event_listener, event: vich_uploader.pre_upload, method: onPreUpload }

    product_bundle.product_attribute_service:
        class: ProductBundle\Service\ProductAttributeService
        arguments: ['@doctrine.orm.entity_manager']

    product_bundle.product_search_service:
        class: ProductBundle\Service\ProductSearchService
        arguments: ['@fos_elastica.finder.noname.product', '@router', '@doctrine.orm.entity_manager', '@twig']

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments: ['@router']