<?php
/**
 * Created by PhpStorm.
 * User: francois
 * Date: 16/08/16
 * Time: 13:08
 */

return $referentiels = [
    'style' => [
        'Boheminan',
        'Campagne chic',
        'Classique',
        'Contemporain',
        'Etnique',
        'Exotique',
        'High tech',
        'Industriel',
        'Modern urbain',
        'Nautique',
        'Pop',
        'Rustique',
        'Scandinave',
        'Shabby chic',
        'Vintage',
        'Zen',
    ],
    'couleur' => [
        '#fff',
        '#FAFAE5',
        '#ECBE83',
        '#FBD55F',
        '#EC6540',
        '#CD2233',
        '#F393BD',
        '#269290',
        '#327D5D',
        '#9CB946',
        '#5F578D',
        '#201E53',
        '#5A4A44',
        '#AFB0AE',
        '#1A170D',
    ],
    'matériau' => [
        'Argent',
        'Bakélite',
        'Bois',
        'Bronze',
        'Céramique, porcelaine & faïence',
        'Cuir',
        'Cuivre',
        'Fer',
        'Fibre de verre',
        'Fonte',
        'Formica',
        'Laiton',
        'Marbre',
        'Métal',
        'Opaline',
        'Papier',
        'Peau',
        'Pierre et plâtre',
        'Plastique',
        'Plexiglas',
        'Rotin et osier',
        'Skaï',
        'Teck',
        'Tissu',
        'Tôle émaillée',
        'Verre et Cristal',
        'Zinc',
    ],
    'designer' => [
        'A + A Cooren',
        'A. Pedretti - Studio Rota & Partners',
        'A.G. Cavalchini',
        'Aalto + Aalto',
        'Aaron Probyn',
        'Abel',
        'Abel Design',
        'Achille Castiglioni',
        'Adalsteinn Stefansson',
        'Adam Cornish',
        'Adam Shirley',
        'Adeline Cacheux',
        'Adolini+Simonini Associati',
        'Adrian Wright',
        'Adriano Baldanzi',
        'Adrien Gardère',
        'Aedasr&D',
        'Afteroom',
        'Agra',
        'Aimé Cécil',
        'Aino-Maija Metsola',
        'Aïssa Logerot',
        'Alain Gilles',
        'Alain Hadife',
        'Alan Van Havre',
        'Alan Chan',
        'Alan Wisniewski',
        'Alberto Meda',
        'Alberto Nason',
        'Alberto Saggia',
        'Alberto Sanchez',
        'Alberto Zecchini',
        'Aldo Bakker',
        'Aldo Ciabatti',
        'Aldo Rossi',
        'Alejandro Ruiz',
        'Aleksej Iskos',
        'Alessandra Baldereschi',
        'Alessandro Dubini',
        'Alessandro Masturzo',
        'Alessandro Mendini',
        'Alessandro Stabile',
        'Alessandro Zambelli',
        'Alex Bergman',
        'Alex Sacchetti',
        'Alex Valder',
        'Alexa Lixfeld',
        'Alexander Taylor',
        'Alexandre Dubreuil',
        'Alfredo Chiaramonte',
        'Alfredo Häberli',
        'Ali Siahvoshi',
        'Alice Abi',
        'Alice Rosignoli',
        'Alissia Melka-Teichroew',
        'All The Way To Paris',
        'Almute Cox',
        'Alvar Aalto',
        'Alyson Fox',
        'Amanda Betz',
        'Amandine Chhor',
        'Ambroise Maggiar',
        'Ana Mir',
        'Ana Roquero',
        'Anamorphée',
        'Anastasia Ivanuk',
        'Ander Lizaso',
        'Anders Lundqvist',
        'Anderssen & Voll',
        'André Bras',
        'André Klauser',
        'Andrea Branzi',
        'Andrea Garuti',
        'Andrea Incontri',
        'Andrea Morgante',
        'Andreas Engesvik',
        'Andreas Lund',
        'Andrée Putman',
        'Andries Hiroko Van Onck',
        'Andries Van Onck',
        'Anette Lang',
        'Angeletti Ruzza',
        'Angelo Mangiarotti',
        'Angelo Natuzzi',
        'Anghini Giovanni Alessi',
        'Anita Dineen',
        'Anita Johansen',
        'Anker Studio',
        'Anna & Gian Franco Gasparini',
        'Anna Castelli Ferrieri',
        'Anna Kraitz',
        'Anna Valsecchi',
        'Anna Von Schewen',
        'Anne Louise Due De Fønss',
        'Anne Sophie Brandt',
        'Anne Holm',
        'Anne Jørgensen',
        'Anne-Claire Petit',
        'Anouk',
        'Anoynym Design',
        'Antoine Lesur',
        'Antoine Phelouzat',
        'Antoine+Manuel',
        'Antoni Palleja Office',
        'Antoni Arola',
        'Antonia Astori',
        'Antonino Sciortino',
        'Antonio Arico',
        'Antonio Astore',
        'Antonio Bonet',
        'Antonio Citterio',
        'Antonio Norero',
        'Antti Kotilainen',
        'Anu Moser',
        'Anu Penttinen',
        'Appree',
        'Aquilialberg',
        'Archikò',
        'Archirivolto Design',
        'Archivio Storico',
        'Ariadna Miquel',
        'Arihiro Miyake',
        'Arik Levy',
        'Arnaud Anseeuw',
        'Arne Jacobsen',
        'Arne Quinze',
        'Arnout Visser',
        'Arthur Leitner',
        'Asociados Lievore',
        'Asshoff & Brogard',
        'Assia Quétin',
        'Atelier 2+',
        'Atelier Oï',
        'Atle Tveit',
        'Audrey Garel',
        'AujourdHui Ou Mardi',
        'Aurélie Dorard',
        'Aurélie Mathigot',
        'Aurélien Barbry',
        'Avichai Tadmor',
        'Avihai Shurin',
        'Axel Delbrayère',
        'Axel Pfaender',
        'Axel Schmid',
        'Ayse Birsel',
        'Aziz Sariyer',
        'B. Hopf',
        'Barba Corsini',
        'Barro De Gast',
        'Bart Schilder',
        'Bartoli Design',
        'Bas Kosters',
        'Basile Graux',
        'Bbmds',
        'Beaverhausen',
        'Ben Mccarthy',
        'Benedetta Mori Ubaldini',
        'Benedetta Tamborini',
        'Benjamin Faure',
        'Benjamin Ferriol',
        'Benjamin Graindorge',
        'Benjamin Hubert',
        'Benny Frandsen',
        'Benoît Convers',
        'Benoît Deneufbourg',
        'Benoît Maignial',
        'Bernadotte&Kylberg',
        'Bernard Schottlander',
        'Bernard-Albin Gras',
        'Bernhard Dessecker',
        'Bernhard Willhelm',
        'Bertjan Pot',
        'Bertocco',
        'Bertrand Balas',
        'Betina Stamp',
        'Biagio Cisotti',
        'Bibi Seck',
        'Bieke Hoet',
        'Big Game',
        'Bill Stumpf',
        'Bina Baitel',
        'Birds For Design',
        'Birger Dahl',
        'Birgit Gämmerler',
        'Björn Dahlström',
        'Björn Hultén',
        'Boje Estermann',
        'Borek Sipek',
        'Böttcher Henssler Kayser',
        'BöTtcher Henssler Kayser',
        'Böttcher+Henssler',
        'Boul Ln',
        'Bower',
        'Boym',
        'Branex Studio',
        'Brian Sironi',
        'Brian Steendyk',
        'Bridgewell Consulting Ltd',
        'Brieuc Du Roscoät',
        'Brigitte De Bazelaire',
        'Britt Bonnesen',
        'Broberg & Ridderstrale',
        'Broersen & Lukács',
        'Brogliato Traverso',
        'Bruno Fattorini & Partners',
        'Bruno Fattorini',
        'Bruno Houssin',
        'Bruno Moretti',
        'Bruno Munari',
        'Bruno Rainaldi',
        'Buro Destruct',
        'Burtscher & Bertolini',
        'By Amt',
        'C + B Lefebvre',
        'C. Denoyelle',
        'Cairn Young',
        'Calvi',
        'Calvi & Brambilla',
        'Camping Design',
        'Carina Seth-Andersson',
        'Carl Jägnefeldt',
        'Carlo Alessi',
        'Carlo Colombo',
        'Carlo Constantini',
        'Carlo Forcolini',
        'Carlo Mollino',
        'Carlo Tamborini',
        'Carlotta De Bevilacqua',
        'Carolina Grassi',
        'Caroline Lisfranc',
        'Caroline Wetterling',
        'Catarina Carreiras',
        'Catellani & Smith',
        'Catherine Denoyelle',
        'Catherine Grandidier',
        'Cathérine Lovatt',
        'Cecil Beaton',
        'Cécile Makowski',
        'Cecilie Manz',
        'Cédric Ragot',
        'Céline Frébault',
        'Cesare Paolini',
        'Chak',
        'Changedesign',
        'Chantal Andriot',
        'Charles Kaisin',
        'Charles Seuleusian',
        'Charles Williams',
        'Charles Wilson',
        'Charlotte Lancelot',
        'Charlotte Perriand',
        'Chauhan Studio',
        'Chen Bikovski',
        'Chen Karlsson',
        'Chiaki Murata',
        'Chris Kabel (Droog Design)',
        'Chris Hardy',
        'Chris Mestdagh',
        'Christian Dell',
        'Christian Flindt',
        'Christian Ghion',
        'Christian Girard',
        'Christian Haas',
        'Christian Theill',
        'Christina Maria Hamel',
        'Christina Halskov',
        'Christina Schäfer',
        'Christoph Matthias',
        'Christophe Mathieu',
        'Christophe Pillet',
        'Christopher Redfern',
        'Chuck Mack',
        'Cini Boeri',
        'Claesson Koivisto Rune',
        'Claire Moreux',
        'Claire-Anne O\'brien',
        'Clara Streim',
        'Clara Von Zweigbergk',
        'Clare Brass',
        'Claudia Raimondo',
        'Claudio Bellini',
        'Claudio Bitetti',
        'Claudio Colucci',
        'Claudio Nardi',
        'Claudio Silvestrin',
        'Claus Bonderup',
        'Claus Simonsen',
        'Clemens Weisshaar',
        'Clive Wilkinson',
        'Clothilde & Julien',
        'Cocktail Designers',
        'Constance Guisset',
        'Constantin + Laurene Boym',
        'Constantin Wortmann',
        'Corinna Warm',
        'Cory Grosser',
        'Cristian Zuzunaga',
        'Cristina Celestino',
        'Cristina Pettenuzzo',
        'Cyril Daniel',
        'D&G Studio',
        'D. Perrucci',
        'Dagmar Mombach',
        'Damian Evans',
        'Damian Williamson',
        'Damien Gernay',
        'Dan Yeffet',
        'Daniel • Emma',
        'Daniel Benito Cortazar',
        'Daniel Gassner',
        'Daniel Hechter',
        'Daniel Kula',
        'Daniel Libeskind',
        'Daniel Rous',
        'Daniel Rybakken',
        'Daniele Bedini',
        'Daniele Gaspardo',
        'Danish Modern 2.0',
        'Danny Fang',
        'Dante Bonuccelli',
        'Dante Donegani',
        'Darling Clementine',
        'David Chipperfield',
        'David Cobbold',
        'David Geckeler',
        'David Hupton',
        'David Trubridge',
        'David Weatherhead',
        'Davide Anzalone',
        'Davide Oldani',
        'Davy Grosemans',
        'De Meuron',
        'De Pas',
        'Decha Archjananun',
        'Deepdesign',
        'Dekoop',
        'Demakersvan',
        'Denis Santachiara',
        'Denton Corker Marshall',
        'Derek Roberts',
        'Design By O',
        'Design Studio 4p1b',
        'Designwright',
        'Dick Van Hoff',
        'Diego Fortunato',
        'Diesel Creative Team',
        'Dik Scheepers',
        'Dimitri Bähler',
        'Ding 3000',
        'Dino Amato',
        'Dirk Wynants',
        'Djordje Cukanovic',
        'Dominique Pinel',
        'Don Chadwick',
        'Donaldwentworth',
        'Donata Paruccini',
        'Donato D\'urbino',
        'Donia Maaoui',
        'Doriana & Massimiliano Fuksas',
        'Douglas Kelley',
        'Douglas Legg',
        'Douwe Jacobs',
        'Droog Design',
        'Duncan Fitzsimons',
        'D\'urbino',
        'Dylan Martorell',
        'Dynomighty',
        'E. Boulmier',
        'E. Gerotto',
        'Eboy',
        'Ecal',
        'Eckard Knuth',
        'Eckhard Knuth',
        'Ed Annink',
        'Ed Carpenter',
        'Edmire',
        'Eduardo Chillida',
        'Edward Barber',
        'Edward Van Vliet',
        'Eero Aarnio',
        'Eero Koivisto',
        'Eija Helande5',
        'Eileen Gray',
        'El Schmid',
        'Elena Salmistraro',
        'Eli Jacobson',
        'Elio Martinelli',
        'Elisa Giovannoni',
        'Elisa Storace',
        'Elisabeth Arkhipoff',
        'Elisabeth Hertzfeld',
        'Elise Berthier',
        'Elise Fouin',
        'Elise Gabriel',
        'Eliumstudio',
        'Elsa Poux',
        'Elvire Laurent',
        'Emaf Progetti',
        'Emanuele Magini',
        'Emili Padros',
        'Emiliana Design Studio',
        'Emiliana Martinelli',
        'Emilio Nanni',
        'Emma Isola',
        'Emma Silvestris',
        'Emmanuel Babled',
        'Emmanuel Gallina',
        'Emmanuel Gardin',
        'Emmanuelle Dupont',
        'Emmanuelle Fouks',
        'Emmanuelle Legavre',
        'En&Ls',
        'Eno Studio',
        'Enrica Frezza',
        'Enrico Azzimonti',
        'Enrico Cesana',
        'Enrico Franzolini',
        'Enzo Berti',
        'Enzo Catellani',
        'Enzo Mari',
        'Ercol Design Studio',
        'Eric Berthes',
        'Eric Carrère',
        'Eric Hibelot',
        'Eric Raffy',
        'Eric Solé',
        'Eric Therner',
        'Erik Magnussen',
        'Erik Olovsson',
        'Erja Hirvi',
        'Ernesto Gismondi',
        'Erwin Termaat',
        'Eskolin-Nurmesniemi',
        'Estd Collection',
        'Ester Horchner',
        'Ettore Sottsass',
        'Eugeni Quitllet',
        'Eva Paster',
        'Fabien Dumas',
        'Fabienne Thonet',
        'Fabio Bortolani',
        'Fabio Meliota',
        'Fabio Novembre',
        'Fabio Rotella',
        'Fabrica',
        'Fabrice Berrux',
        'Falke Svatun',
        'Farkas Pongrácz',
        'Fattorini + Rizzini + Partners',
        'Favaretto Studio',
        'Federica Capitani',
        'Federico Traverso',
        'Felice Buelli',
        'Fellina Sok-Cham',
        'Ferdi Giardini',
        'Fermob',
        'Fernando Brizio',
        'Ferréol Babin',
        'Ferruccio Laviani',
        'Filip Janssens',
        'Filippo Castellani',
        'Filippo Protasoni',
        'Finn Magee',
        'Finn Stone',
        'Flavio Lucchini',
        'Florence Béchet',
        'Florence Bourel',
        'Florence Deygas',
        'Florence Manlik',
        'Florence Watine',
        'Florent Bouhey Fayolle',
        'Florentijn Hofman',
        'Floris Hovers',
        'Floyd',
        'Flynn Talbot',
        'Form Us With Love',
        'Format Design Studio',
        'Formfjord',
        'Formfusion',
        'Formnation',
        'Formstelle',
        'Foster & Partners',
        'Frama Studio',
        'Francesca Amfitheatrof',
        'Francesca Braga Rosa',
        'Francesco Bettoni',
        'Francesco Binfaré',
        'Francesco Faccin',
        'Francesco Giannattasio',
        'Francesco Lucchese',
        'Francesco Pavia',
        'Francesco Rota',
        'Francis Cayouette',
        'Francisco Gomez Paz',
        'Francisco Gomez',
        'Franck Gehry',
        'Franco Albini',
        'Franco Raggi',
        'Franco Sargiani',
        'Franco Teodoro',
        'Francois Azambourg',
        'François Champsaur',
        'François Clerc',
        'François Dumas',
        'François Mangeol',
        'Frank',
        'Frank O. Gehry',
        'Frank Person',
        'Frank Rettenbacher',
        'Frans Van Nieuwenborg',
        'Fransisco Corvi',
        'Franz Ringelhan',
        'Franziska Fuchs',
        'Fratelli Campana',
        'Fred Lip',
        'Frédéric Gaunet',
        'Frederic Gooris',
        'Frédéric Lintz',
        'Fréderic Malphettes',
        'Frédéric Perigot',
        'Frédéric Ruyant',
        'Frédéric Sofia',
        'Frédéric Verdys',
        'Frederico Floriani',
        'Frederico Grazzini',
        'Fredrikson Stallard',
        'Fresh West',
        'Front',
        'Frost Produkt',
        'Fumie Shibata',
        'Furi Furi',
        'Future Systems',
        'Fx Balléry',
        'G. Reichert',
        'Gabi Peretto',
        'Gabriel Nigro',
        'Gabriel Teixidó',
        'Gabriele Chiave',
        'Gabriele Rosa',
        'Gae Aulenti',
        'Gaëlle Gabillet',
        'Gaku Otomo',
        'Galli & Perico',
        'Gamfratesi',
        'Gamplusfratesi',
        'Gardin Nicola',
        'Garth Roberts',
        'Gary Chang',
        'Gaston Cavaillon',
        'Geneviève Gauckler',
        'Geof Ramsay',
        'Georg Baldele',
        'George J. Sowden',
        'George Carwardine',
        'Gerard Moliné',
        'Gerardo Mari',
        'Gerd Van Cauteren',
        'Gesa Hansen',
        'Giancarlo Fassina',
        'Giancarlo Mattioli',
        'Gianfranco Frattini',
        'Gianluca Soldi',
        'Gianni Rossi',
        'Gianpetro Gai',
        'Giel Dedeurwaerder',
        'Gilles Derain',
        'Gillian Westley',
        'Gino Colombini',
        'Giò Colonna Romano',
        'Gio Ponti',
        'Giogia Zanellato',
        'Giordana Arcesilai',
        'Giorgio Biscaro',
        'Giorgio Bonaguro',
        'Giorgio Vigna',
        'Giotto Stoppino',
        'Giovanni Lauda',
        'Giovanni Levanti',
        'Giovanni Minelli',
        'Gisa Wilken',
        'Giulia Angoletto',
        'Giulio Cappellini',
        'Giulio Iacchetti',
        'Giuseppe Maurizio Scutellà',
        'Giuseppe Chigiotti',
        'Godefroy De Virieu',
        'Golden Green',
        'Goodmorning Technology',
        'Goodwin Hartshorn',
        'Goran Lelas',
        'Gordon Tait',
        'Goula & Figuera',
        'Graeme Davies',
        'Grafite Design',
        'Graziano Moro',
        'Greg Lynn',
        'Gregorio Spini',
        'Greta Magnusson Grossman',
        'Grethe Meyer',
        'Griffik',
        'Grisella Kreiterling',
        'Grito El Ultimo',
        'Group Italia',
        'Grupa',
        'Gubi Design Team',
        'Gud Studio',
        'Guglielmo Berchicci',
        'Guido Bianchi',
        'Guido Matta',
        'Guido Venturini',
        'Guillaume Delvigne',
        'Gustav Hallen',
        'Guy Savoy',
        'Guzzini Lab',
        'H. Ubbens',
        'H5',
        'Habits Studio',
        'Hagai Zakai',
        'Hagen Sczech',
        'Han Yumin',
        'Hani Rashid',
        'Hanna Ehlers',
        'Hanna Ernsting',
        'Hanne Dalsgaard',
        'Hannes Beer',
        'Hans Werner Holzwarth',
        'Hans Bleken Rud',
        'Hans Dukkers',
        'Hans Hornemann',
        'Hans Sandgren Jakobsen',
        'Hans Thyge Raunkjaer',
        'Hans Weyers',
        'Hansjerg Maier-Aichen',
        'Harald Guggenbichler',
        'Hareide Design',
        'Harri Koskinen',
        'Harry & Camila',
        'Hay Studio',
        'Headsprung',
        'Héctor Serrano',
        'Hedda H. Braathen',
        'Hee Welling',
        'Heikki Orvola',
        'Hein Eek Piet',
        'Helga Sigurbjarnadottir',
        'Hella Jongerius',
        'Helmo',
        'Henk Stallinga',
        'Henri Kloss',
        'Henrik Pedersen',
        'Henry Massonnet',
        'Herbert Krenchel',
        'Herman Studio',
        'Hertel & Klarhoefer',
        'Hervé Langlais',
        'Herzog',
        'Hidenori Kuge',
        'Hilton Mcconnico',
        'Hints',
        'Hollandsche Waaren',
        'Holmbäcknordentoft',
        'Homstvedt Hallgeir',
        'Hsu-Li Teo',
        'Hulger',
        'I. Borovnjak & R. Bratović',
        'Ich & Kar',
        'Ichiro Iwasaki',
        'Ida Elke',
        'Iguzzini',
        'Ilaria Innocenti',
        'Ilaria Marelli',
        'Ilkka Suppanen',
        'Ilse Lang',
        'Imma Bermúdez',
        'India Mahdavi',
        'Industrial Facility',
        'Ineke Hans',
        'Ines De La Fressange',
        'Inga Sempé',
        'Ingela P. Arrhenius',
        'Ingo Maurer',
        'Ionna Vautrin',
        'Ippolito Fleitz & Tilla Goldberg',
        'Irene Bacchi',
        'Iris De Moüy',
        'Iroko Takeda',
        'Isabella Lovero',
        'Isao Hosoe',
        'Iskos-Berlin',
        'Issey Miyake',
        'Italo Pertichini',
        'Itamar Harari',
        'Ivan Kasner',
        'Ivan Liechti',
        'Ivano Vianello',
        'Jacob Jensen',
        'Jacob Rudbeck',
        'Jacopo Zibardi',
        'Jacques Adnet',
        'Jaime Hayón',
        'Jake Phipps',
        'Jakob Heiberg',
        'Jakob Jorgensen',
        'Jakob Munk',
        'Jakob Wagner',
        'James Bartlett',
        'James Irvine',
        'Jan & Henry',
        'Jan & Lara',
        'Jan Christian Delfs',
        'Jan Armgardt',
        'Jan Bazing',
        'Jan Hansen',
        'Jan Hoekstra',
        'Jan Kochanski',
        'Jannis Ellenberger',
        'Jarrod Lim',
        'Jasper Morrison',
        'Javier Mariscal',
        'Javier Moreno',
        'Javier Tortosa',
        'Jay Osgerby',
        'Jc Golf',
        'Jds Architects',
        'Jean Baptiste Auvray',
        'Jean Melis',
        'Jean Nouvel',
        'Jean Pauchard',
        'Jean-Baptiste Fastrez',
        'Jean-Charles Amey',
        'Jean-François Bellemère',
        'Jean-Jacques Hubert',
        'Jean-Louis Domecq',
        'Jean-Louis Iratzoki',
        'Jean-Marie Massaud',
        'Jean-Michel Wilmotte',
        'Jeanne Bonnefoy-Mercuriali',
        'Jean-Sébastien Poncet',
        'Jean-Yves Le Porcher',
        'Jehs & Laub',
        'Jennifer Rabatel',
        'Jens Fager',
        'Jens Widerberg',
        'Jeremy Wright',
        'Jeremyville',
        'Jeroen Van De Kant',
        'Jerszy Seymour',
        'Jesper Ståhl',
        'Jim Hannon-Tan',
        'Jimenez Vicente Garcia',
        'Jo Hammerborg',
        'Joacim Wahlström',
        'Joan Gaspar',
        'Joan Gasper',
        'Joanna Lyle',
        'Joaquim Ruiz Millet',
        'Jocelyn Deris',
        'Jody Barton',
        'Joe Boxer',
        'Joe Colombo',
        'Joe Doucet',
        'Joel Degermark',
        'Joel Hoff',
        'Johan Ridderstrale',
        'Johanna Grawunder',
        'John & Samantha Ritschl-Lassoudry',
        'John Brauer',
        'John Green',
        'John Pawson',
        'John Truex',
        'Jon Burgerman',
        'Jonas Forsman',
        'Jonas Trampedach',
        'Jonas Wagell',
        'Jonathan Adler',
        'Jonathan Levien',
        'Jonathan Olivares',
        'Jonathan Sabine',
        'Jonathon Aspinall',
        'Jonghwan Kim',
        'Joost Van Bleiswijk',
        'Joran Briand',
        'Jordan Murphy',
        'Jordi Lopez',
        'Jordi Vilardell',
        'Jörg Gätjens',
        'Jorge Ferrari-Hardoy',
        'Jorge Herrera',
        'Jorge Najera',
        'Jorgen Baekmark',
        'Jorgen Ditzel',
        'Jorn Utzon',
        'Jose Manuel Ferrero',
        'Josef Hoffmann',
        'Joseph Llusca',
        'Josha Roymans',
        'Jozeph Forakis',
        'Juan Carlos Viso',
        'Juan Kurchan',
        'Jukka Setälä',
        'Jules Julien',
        'Julien De Smedt',
        'Julien Michel',
        'Julien Phedyaeff',
        'Juliette Swildens',
        'Jullien Thaler',
        'Jurgen Bey',
        'K. Laville',
        'Ka-Lai Chan',
        'Kaptein Roodnat',
        'Karen Olze',
        'Karim Rashid',
        'Karin Santorso',
        'Karl Malmvall',
        'Karri Monni',
        'Kaschkasch Cologne',
        'Kasper Nyman',
        'Kasper Salto',
        'Kateryna Sokolova',
        'Katsuji Wakisaka',
        'Kaz Lorenz',
        'Kazoil',
        'Kazuhiro Yamanaka',
        'Kazuya Koike',
        'Kazuyo Sejima',
        'Keji Ashizawa',
        'Kenneth Grange',
        'Kenyon Yeh',
        'Kerstin Horlin Holmquist',
        'Khodi Feiz',
        'Kibisi',
        'Kihyun Kim',
        'King Kong Design',
        'Kings',
        'Klaus Haapaniemi',
        'Klaus Hackl',
        'Klaus Rath',
        'Klauss Begasse',
        'Klein + Leidig',
        'Köbi Wiesendanger',
        'Koen Baeyens',
        'Koichi Futatsumata',
        'Köln Dreikant',
        'Komplot Design',
        'Konstantin Grcic',
        'Koray Ozgen',
        'Kotaro Usugami',
        'Koziol',
        'Koziol Werksdesign',
        'Kravitz Design',
        'Kristian Aus',
        'Kristian Gavoille',
        'Kristina Isola',
        'Kristina Kjaer',
        'Kristina Lassus',
        'Kustaa Saksi',
        'Kyuhyung Cho',
        'L. Bozzoli',
        'L. Reich',
        'L. Sonnoli',
        'La Boîte Concept',
        'Lab81',
        'Lacie',
        'Lagranja Design',
        'Lapo Ciatti',
        'Lars Beller Fjetland',
        'Lars Tornoe',
        'L\'atelier D\'exercices - Studio',
        'L\'atelier Du Vin',
        'Laudani & Romanelli',
        'Läufer + Keichel',
        'Laura Pessoni',
        'Laurence Brabant',
        'Laurence Jaccottet',
        'Laurence Vayson',
        'Laurens Van Wieringen',
        'Laurent Bailly',
        'Laurent Batisse',
        'Laurent Baulé',
        'Laurent Corio',
        'Laurent Lévêque',
        'Laurent Massaloux',
        'Lazy Smith',
        'Le Corbusier',
        'Le Deun Luminaires',
        'Le Duo',
        'Lee Storm',
        'Lee West',
        'Lei Zhang',
        'Leif Hansen',
        'Leif Jorgensen',
        'Leon Ramakers',
        'Leon Ransmeier',
        'Leonard Aldenhoff',
        'Leonardo',
        'Les Graphiquants',
        'Leslie David',
        'Lex Pott',
        'Lexon Studio',
        'Lieven Musschoot',
        'Lievore Altherr Molina',
        'Lili Gayman',
        'Liliana Bonomi',
        'Lilli Bertoni',
        'Line Depping',
        'Lineeverdi',
        'Liran Levi',
        'Lisa Bellon',
        'Lisa Vincitorio',
        'Livio Castiglioni',
        'Lluis Clotet',
        'Lluis Porqueras',
        'Loetizia Censi',
        'Löfgren Magnus',
        'Lomazzi',
        'Lorenzo Arosio',
        'Lorenzo Bustillos',
        'Lorenzo Piccione Di Pianogrillo',
        'Loris & Livia',
        'Lotta Olsson',
        'Louis Poulsen',
        'Louise Campbell',
        'Louise Christ',
        'Loulou & Tummie',
        'Lovisa Hansson',
        'Lovorika Banovic',
        'Lpwk',
        'Luc Jozancy',
        'Luc Moulin',
        'Luc Ramael',
        'Luca Bini',
        'Luca Galbusera',
        'Luca Nichetto',
        'Luca Pevere',
        'Luca Trazzi',
        'Lucian Ercolani',
        'Luciano Bertoncini',
        'Luciano Marson',
        'Lucidi Pevere',
        'Lucidipevere Studio',
        'Lucie Koldova',
        'Lucien Gumy',
        'Ludovic Roth',
        'Ludovica & Roberto Palomba',
        'Luigi Barei',
        'Luigi Baroli',
        'Luigi Caccia Dominioni',
        'Luisa Bocchietto',
        'Luka Or',
        'M. Luck',
        'M. Rivier',
        'Ma Yan Song',
        'Maarten Baas',
        'Maarten Baptist',
        'Maarten De Ceulaer',
        'Maartje Steenkamp',
        'Made By Makers',
        'Made By Michael',
        'Magali Arbib',
        'Magnus Pettersen',
        'Maija Isola',
        'Maija Louekari',
        'Maison Christian Lacroix',
        'Maison Georgette',
        'Maison Martin Margiela',
        'Mann Singh',
        'Manuela Busetti',
        'Manuela Di Loreto',
        'Marc A. Thorpe',
        'Marc Berthier',
        'Marc Krusin',
        'Marc Newson',
        'Marc Sadler',
        'Marc Sarrazin',
        'Marc Venot',
        'Marcantonio Raimondi Malerba',
        'Marcel Wanders',
        'Marcello Jori',
        'Marcello Ziliani',
        'Marco Acerbis',
        'Marco Colombo',
        'Marco Ferreri',
        'Marco Marin',
        'Marco Zanatta',
        'Marco Zanuso',
        'Marco Zito',
        'Marga Van Oers',
        'Margrethe Odgaard',
        'Maria Berntsen',
        'Maria Sanchez',
        'Marian Bantjes',
        'Marie Desplechin',
        'Marie Michielssen',
        'Marie-Aurore Stiker-Metral',
        'Marie-Cerise Lichtlé',
        'Marie-Christine Dorner',
        'Marie-Louise Gustafsson',
        'Mario Barbaglia',
        'Mario Bellini',
        'Mario Botta',
        'Mario Ruiz',
        'Mario Trimarchi',
        'Mario Tsai',
        'Marion Courtillé',
        'Mark Braun',
        'Mark Robson',
        'Mark Sanders',
        'Mark Verhaagen',
        'Mark Wedel',
        'Markku Salo',
        'Markus Schmidt',
        'Mars Design Studio',
        'Marta Sansoni',
        'Marti Guixé',
        'Martin Azua',
        'Martin Dos Santos',
        'Martin Kallin',
        'Martine Bedin',
        'Martino Gamper',
        'Marzano',
        'Marzia Et Leonardo Dainelli',
        'Massimiliano Settimelli',
        'Massimo Barbierato',
        'Massimo Giacon',
        'Massimo Mariani',
        'Massimo Tassone',
        'Matali Crasset',
        'Mathias Hahn',
        'Mathias Hennebel',
        'Mathias Van De Walle',
        'Mathieu Gustafsson',
        'Mathieu Lehanneur',
        'Mathieu Matégot',
        'Matilda Lindblom',
        'Mats Broberg',
        'Matt Carr',
        'Matteo Borghi',
        'Matteo Nunziati',
        'Matteo Ragni',
        'Matteo Redaelli',
        'Matteo Thun',
        'Matthew Hilton',
        'Matthias Demacker',
        'Matti Klenell',
        'Mattia Di Rosa',
        'Mattias Stahlbom',
        'Mattias Stenberg',
        'Mauricio Klabin',
        'Maurizio Cattelan',
        'Maurizio Galante',
        'Maurizio Peregalli',
        'Mauro Lipparini',
        'Max Ingrand',
        'Max Lipsey',
        'Maximilian Schmahl',
        'Melchoff Bahnsen & Fog-Fredsgaard',
        'Menguzzato & Nascimben',
        'Meritxell Vidal',
        'Merlini',
        'Mermeladaestudio',
        'Metermorphosen',
        'Metis',
        'Mette Duedahl',
        'Meyer Design',
        'Michael Anastassiades',
        'Michael Geldmacher',
        'Michael Graves',
        'Michael Hilgers',
        'Michael Lin',
        'Michael Young',
        'Michel Arnoult',
        'Michel Boucquillon',
        'Michel Boyer',
        'Michel Buffet',
        'Michele Cazzaniga',
        'Michele De Lucchi',
        'Mika Tolvanen',
        'Mikaela Dörfel',
        'Miki Astori',
        'Mikko Kärkkäinen',
        'Milia Seyppel',
        'Milodamalo',
        'Minedivine',
        'Minedivinie Associati',
        'Mira Heinze',
        'Miriam Mirri',
        'Moe Takemura',
        'Monica Battistella',
        'Monica Förster',
        'Monica Graffeo',
        'Monkey Business',
        'Moooi Works',
        'Moredesign',
        'Moritz Waldemeyer',
        'Morph',
        'Morten & Jonas',
        'Morten Kildahl',
        'Moschino',
        'Moya',
        'Msds',
        'Murken Hansen',
        'Murkenhansen',
        'Musuta',
        'Mut Design',
        'Mvw',
        'Nachacht Berlin',
        'Nacho Carbonell',
        'Nadia Arrabitel',
        'Nadia Arratibel',
        'Nana Gröner',
        'Nani Marquina',
        'Nanna Ditzel',
        'Nanni Holen',
        'Naoko Shintani',
        'Naoto Fukasawa',
        'Naoya Matsuo',
        'Nathalie Daniel',
        'Nathalie Du Pasquier',
        'Nathalie Lété',
        'Nathan Yong',
        'Neil Poulton',
        'Nendo',
        'Neri & Hu',
        'Neue Freunde',
        'Neuland',
        'Neuland, Paster & Geldmacher',
        'Neunzig',
        'Nicholai Wiig Hansen',
        'Nick Macdonald',
        'Nicola Design',
        'Nicola Bonriposi',
        'Nicolas Girard',
        'Nicolas Le Nocher',
        'Nicolas Mauriac',
        'Nicolas Pichelin',
        'Nicolas Vahé',
        'Nicole Van Schouwenburg Et Irene Klinken',
        'Nicoletta Rossi',
        'Niels Kjeldsen',
        'Nika Zupanc',
        'Nils Strinning',
        'Nina Jobs',
        'Ninon Leclerc',
        'Nipa Doshi',
        'Nis Fischer',
        'Nl Architects',
        'Noé Duchaufour Lawrance',
        'Noidoi',
        'Norayr Khachatyran',
        'Noriko Hashida',
        'Norm',
        'Norm Arkitekter',
        'Normal Studio',
        'Normaluisa',
        'Norman Trapman',
        'Norway Says',
        'Note Design Studio',
        'Numen/Foruse',
        'Nuova Città',
        'Nur',
        'Oded Friedland',
        'Odile Decq',
        'Odoardo Fioravanti',
        'Odosdesign',
        'Officeoriginair',
        'Oiva Toikka',
        'Øivind Alexander Slaatto',
        'Øivind Slaatto',
        'Oka Doner',
        'Olaf Von Bohr',
        'Ole Jensen',
        'Ole Palsby',
        'Olivia Putman',
        'Olivier Chabaud',
        'Olivier Gagnère',
        'Olivier Grégoire',
        'Olivier Kuntzel',
        'Olivier Peyricot',
        'Ondarreta Team',
        'Ontwerpduo',
        'Opera W. In P.',
        'Ora Ito',
        'Ori Saidi',
        'Orlandini Design',
        'Örni Halloween',
        'Oscar Diaz Melon',
        'Oshiro Kensaku',
        'Ototo',
        'Otto Blumel',
        'Ove Rogne',
        'Ox-Id',
        'P. Pallucco',
        'P.Mendes Da Rocha',
        'Pagnon & Pelhaître Design',
        'Pamio Design',
        'Pandarosa',
        'Pan-G Design',
        'Paola Di Arianello',
        'Paola Navone',
        'Paola Suhonen',
        'Paolo Cappello',
        'Paolo De Lucchi',
        'Paolo Dell\'elce',
        'Paolo Gerosa',
        'Paolo Golinelli',
        'Paolo Grasselli',
        'Paolo Imperatori',
        'Paolo Lomazzi',
        'Paolo Lucidi',
        'Paolo Rizzatto',
        'Paolo Zani',
        'Park Associatti',
        'Pascal Grossiord',
        'Pascal Mourgue',
        'Pascal Tarabay',
        'Pascual Salvador',
        'Patrice Hardy',
        'Patricia Urquiola',
        'Patrick Frey',
        'Patrick Jouin',
        'Patrick Morris',
        'Patrick Nadeau',
        'Patrick Norguet',
        'Paul Cocksedge',
        'Paul Leroy',
        'Paul Newman',
        'Paul Rowan',
        'Pauline Deltour',
        'Pauline Gilain',
        'Paulo Mariotti',
        'Pedrizetti & Associati',
        'Peggy Huyn Kinh',
        'Peleg Design',
        'Pellegrini+Mengato Design',
        'Pengelly Design',
        'Pentagon Design',
        'Pepa Prieto',
        'Pepe Heykoop',
        'Perrine Vigneron',
        'Pete Sans',
        'Peter Gaebelein',
        'Peter Joebsch',
        'Peter Johansen',
        'Peter Koehl',
        'Peter Orsig',
        'Peter Shire',
        'Peter Stathis',
        'Peter Van Der Jagt',
        'Peter Zumthor',
        'Petite Friture',
        'Phil Luithlen',
        'Philip Bro',
        'Philip Wong',
        'Philippe Bestenheider',
        'Philippe Cuendet',
        'Philippe Nigro',
        'Philippe Starck',
        'Pier Giacomo Castiglioni',
        'Pierfrancesco Cravel',
        'Piergil Fourquié',
        'Piergiorgio Cazzaniga',
        'Piero Castiglioni',
        'Piero De Gatti',
        'Piero Lissoni',
        'Pierpaolo Ferrari',
        'Pierre Casenove',
        'Pierre Charpin',
        'Pierre De Poucques',
        'Pierre Dubois',
        'Pierre Dubourg',
        'Pierre Favresse',
        'Pierre Gagnaire',
        'Pierre Garner',
        'Pierre Gonalons',
        'Pierre Hermé',
        'Pierre Marie',
        'Pierre Paulin',
        'Pierre Stadelmann',
        'Pierre-François Dubois',
        'Piet Boon',
        'Piet Hein Eek',
        'Pietro Derossi',
        'Piks Design',
        'Pinkeye',
        'Pio & Tito Toso',
        'Pio Manzu',
        'Platt',
        'Polka',
        'Pols Potten',
        'Pontus Ny',
        'Pool',
        'Poul M. Volther',
        'Poul Henningsen',
        'Powerhouse Company',
        'Prandina R&D',
        'Prospero Rasulo',
        'Pudelskern',
        'Puzzle 4 Peace',
        'Qed-Design',
        'Quaglio Simonelli',
        'Queensberry Hunt Levien',
        'R. Tedesco',
        'Rachel Convers',
        'Raf Simons',
        'Rafael Rodriguez',
        'Rafaella Mangiorotti',
        'Raffaele Celentano',
        'Raffaella Mangiarotti',
        'Rafic Farah',
        'Raimond Puts',
        'Rainer Lehn',
        'Rajiv Saini',
        'Ramon Benedito',
        'Ramon Esteve',
        'Ramos & Bassols',
        'Ransmeier',
        'Raoul Raba',
        'Raphaël Charles',
        'Rasmus Gottliebsen',
        'Raul Barbieri',
        'Raw Edges',
        'Reality Lab',
        'Red Garbo',
        'Reda Amalou',
        'Reddish Studio',
        'Redesign',
        'Relja Arnautovic',
        'Rémi Fontaine',
        'Renate Vos',
        'Renato Pigatti',
        'Renaud Bonzon',
        'René Barba',
        'Reto Schöpfer',
        'Ricardo Blumer',
        'Riccardo Sarfatti',
        'Richard Hutten',
        'Richard Sapper',
        'Richard Woods',
        'Rikke Frost',
        'Rikke Hagen',
        'Rikke Malling',
        'Rinzen',
        'Rmp Associates',
        'Rob Brandt',
        'Rob Flowers',
        'Rob Slewe',
        'Robert Dudley Best',
        'Robert Bronwasser',
        'Robert Ryan',
        'Robert Wengler',
        'Roberta Rampazzo',
        'Roberto Barbieri',
        'Roberto Giacomucci',
        'Roberto Menghi',
        'Roberto Paoli',
        'Roberto Tognon',
        'Robin Levien',
        'Robin Platt',
        'Robin Rizzini',
        'Roderick Fry',
        'Roderick Vos',
        'Rodolfo Agrella',
        'Rodolfo Bonetto',
        'Rodolfo Dordoni',
        'Rodrigo Torres',
        'Roger Tallon',
        'Roger Zanon',
        'Rogier Van Male',
        'Roland Kreiter',
        'Rolito',
        'Roman Pin',
        'Romano Gio Colonna',
        'Romano Marcato',
        'Ron Arad',
        'Ron Gilad',
        'Ronan & Erwan Bouroullec',
        'Røpke Design',
        'Rosaria Copeta',
        'Ross Littell',
        'Ross Lovegrove',
        'Ruggero Magrini',
        'Rumiko Takeda',
        'Russel Cameron',
        'Ryue Nishizawa',
        'S & R Cornelissen',
        'S. Chanchus',
        'Salvatore Indriolo',
        'Sam Baron',
        'Sam Hecht',
        'Sami Kallio',
        'Sami Ruotsalainen',
        'Sami Wirkkala',
        'Samuel Accoceberry',
        'Samuel Wilkinson',
        'Sandra Figuerola',
        'Sandra Lindner',
        'Sandrine Alouf',
        'Sandrine Fabre',
        'Sandro Chia',
        'Sandro Colbertaldo',
        'Sanja Knezovic',
        'Santiago Calatrava',
        'Sara Bernardi',
        'Sarah Böttger',
        'Sarah Lavoine',
        'Sascha Sartory',
        'Saskia Van Der Linden',
        'Satyendra Pakhalé',
        'Saverio Incombenti',
        'Says Who',
        'Scholten & Baijings',
        'Schwarz Späth',
        'Scott Wilson',
        'Sean Yoo',
        'Sebastian Bergne',
        'Sebastian Errazuriz',
        'Sebastian Herkner',
        'Sebastian Wrong',
        'Sébastien Cordoléani',
        'Sébastien Durand-Viel',
        'Selab',
        'Sentou',
        'Seppo Koho',
        'Serge Atallah',
        'Serge Bensimon',
        'Serge Mouille',
        'Sergio Gobbi',
        'Sergio Mazza',
        'Sergio Valsecchi',
        'Setsu & Shinobu Ito',
        'Seventh Sense',
        'Sezgin Aksu',
        'Shahar Peleg',
        'Shane Schneck',
        'Shay Alkalay',
        'Shin & Tomoko Azumi',
        'Shin Azumi',
        'Shiro Kuramata',
        'Shoichi Uchiyama',
        'Sidse Werner',
        'Signe Hytte',
        'Sigrid Smetana',
        'Sigurjón Pálsson',
        'Silo Studio',
        'Silvia Suardi',
        'Silvio Coppola',
        'Simon Key Bertman',
        'Simon Legald',
        'Simon Morasi Piperčić',
        'Simon Pengelly',
        'Simon Wilkinson',
        'Simone Micheli',
        'Simone Spalvieri',
        'Simple Human',
        'Sitrum Design',
        'Sjoerd Vroonland',
        'Slide Design',
        'Smithmatthias',
        'Sofie Refer',
        'Soledad',
        'Sonia Rykiel',
        'Sonia Verguet',
        'Sonya Pletes',
        'Søren Rose Studio',
        'Søren Refsgaard',
        'Soren Rose',
        'Sottsass Associati Design',
        'Space Copenhagen',
        'Spant Studio',
        'Staffan Holm',
        'Stefan Bench',
        'Stefan Diez',
        'Stefan Geisbauer',
        'Stefan Kaiser',
        'Stefania Di Petrillo',
        'Stefano Giovannoni',
        'Stelton',
        'Stephan Lanez',
        'Stéphane Joyeux',
        'Stéphane Villard',
        'Stéphanie Marin',
        'Stephen Burks',
        'Steve Blackman',
        'Steve Lechot',
        'Steve Mcgugan',
        'Steven Blaess',
        'Steven Holl',
        'Sth',
        'Stig Ahlström',
        'Stijn Goethals',
        'Stone Designs',
        'Studio 63',
        'Studio Badini Creatim',
        'Studio Boot',
        'Studio Brichetziegler',
        'Studio Crouscalogero',
        'Studio Ctrlzak',
        'Studio Designlab',
        'Studio Dessuant Bone',
        'Studio Diamantini & Domeniconi',
        'Studio Dreimann',
        'Studio Drift',
        'Studio Ea',
        'Studio Frandsen',
        'Studio Frst',
        'Studio Garcia-Cumini',
        'Studio Job',
        'Studio Joe Colombo',
        'Studio Kees',
        'Studio Klass',
        'Studio Kluif',
        'Studio Kristina Dam',
        'Studio Labyrinth',
        'Studio Natural',
        'Studio Nitzan Cohen',
        'Studio Nocc',
        'Studio Paul',
        'Studio Poiat',
        'Studio Pp',
        'Studio Qed',
        'Studio Simple',
        'Studio Sputnik',
        'Studio Tb',
        'Studio Tecnico Magis',
        'Studio Thun',
        'Studio Tonino',
        'Studio Vaulot & Dyèvre',
        'Studio Vit',
        'Studio Wm',
        'Studio Beretta',
        'Studio17',
        'Studiopang',
        'Sung Wook Park',
        'Supercraft Studio',
        'Superstudio',
        'Surplus Systems',
        'Susan Cohn',
        'Susan Potts',
        'Susanne Stofer',
        'Sven Ivar Dysthe',
        'Sybilla',
        'Sylvain Willenz',
        'T. Biallas',
        'Tado',
        'Taf Architects',
        'Tak Cheung',
        'Takashi Shinozaki',
        'Tal Lancman',
        'Tania & Vincent',
        'Tapio Wirkkala',
        'Tatsuo Kuroda',
        'Téjo Remy',
        'Teppo Asikainen',
        'Terence Conran',
        'Terry Dwan',
        'Tetsuo Shibuya',
        'The Tools',
        'Theo Williams',
        'Theresa Arns',
        'Thesevenhints',
        'Thinkk Studio',
        'Thomas Bentzen',
        'Thomas Bernstrand',
        'Thomas Eurlings',
        'Thomas Heatherwick',
        'Thomas Hourdain',
        'Thomas Jelinek',
        'Thomas Junk',
        'Thomas Kral',
        'Thomas Merlin',
        'Thomas Sauvage',
        'Thomas Schnur',
        'Thomas Tchaban',
        'Tiffany Cooper',
        'Timo Sarpaneva',
        'Timorous Beasties',
        'Tina Leung',
        'Tina Ratzer',
        'Tino Valentinitsch',
        'Tio',
        'Tiphaine De Bodman',
        'Tito Agnoli',
        'Toan Nguyen',
        'Tobia Scarpa',
        'Tobias Juretzek',
        'Tobias Tøstesen',
        'Todd Bracher',
        'Todo',
        'Tokujin Yoshioka',
        'Tom Devesto',
        'Tom Dixon',
        'Tom Kovac',
        'Tom Schouten',
        'Tomita Kazuhiko',
        'Tommaso Bistacchi',
        'Tommaso Caldera',
        'Torafu Architects',
        'Tord Boontje',
        'Torsten Thorup',
        'Tous Les Trois',
        'Toyo Ito',
        'Trafik',
        'Trendform',
        'Trine Andersen',
        'Tristan Lohner',
        'Trond Svendgard',
        'Tsé-Tsé',
        'Tuna Paper',
        'Tveit & Tornoe',
        'Ufficio Tecnico',
        'Ufficio Tecnico Alessi',
        'Ufficio Tecnico Kartell',
        'Ulrika Gustafsson',
        'Un Studio',
        'Valentina Carretta',
        'Valentina Del Ciotto',
        'Valérie Windeck',
        'Valerio Cometti',
        'Valerio Sommella',
        'Van Strien Anne',
        'Vera & Kyte',
        'Verner Panton',
        'Veronika Wildgruber',
        'Véronique Maire',
        'Vibeke Fonnesberg Schmidt',
        'Vico Magistretti',
        'Victor Carrasco',
        'Victor Vasilev',
        'Victor Vetterlein',
        'Victoria Delani',
        'Victoria Wilmotte',
        'Vierdeedesign',
        'Viggo Boesen',
        'Vigo Nanda',
        'Villa Tosca Design',
        'Vim & Vigor',
        'Vincent Van Duysen',
        'Vincent Vandenbrouck',
        'Vittorio Locatelli',
        'Vittorio Massimo',
        'Vittorio Venezia',
        'Vogt',
        'Voon Wong',
        'Voutch',
        'Weizenegger',
        'Wendy Boudewijns',
        'Werner Aisslinger',
        'Whatswhat',
        'Wieki Somers',
        'Wiel Arets',
        'Wien',
        'Willi Glaeser',
        'William Alsop',
        'William Katavolos',
        'Winnie Lui',
        'Wis Design',
        'Wrk-Shp',
        'Xavier Lust',
        'Xavier Pauchard',
        'Xie Dong',
        'Xuclà',
        'Yaacov Kaufman',
        'Yaroslav Rassadin',
        'Yohei Oki',
        'Youngsun',
        'Yoy',
        'Yung Ho Chang',
        'Yve Thelermont',
        'Yves Malka',
        'Zaha Hadid',
        'Zmik',

    ],
    'marque' => [
        '& Klevering',
        'Aa-New Design',
        'Adelta',
        'Alberta',
        'Alessi',
        'Alias',
        'Alki',
        'And Tradition',
        'Anglepoise',
        'Anne-Claire Petit',
        'Antonangeli',
        'Arco',
        'Areaware - Pop Corn',
        'Arper',
        'Artek',
        'Artemide',
        'Artisan',
        'Artuce',
        'Authentics',
        'Aytm',
        'Azimut Industries',
        'Babyhome',
        'Bacsac',
        'Bazar Therapy',
        'Belux',
        'B-Line',
        'Blofield',
        'Bloom!',
        'Bloom Baby',
        'Bloomingville',
        'Bluelounge',
        'Bob Design',
        'Branex',
        'Brokis',
        'Budtzbendix',
        'Cacoon',
        'Cantori',
        'Casamania',
        'Catellani & Smith',
        'baleri-italia',
        'Chevalier Edition',
        'Christofle',
        'Cinna',
        'Classicon',
        'Collinet',
        'Cookplay',
        'Dall\'agnese',
        'Danese',
        'David Trubridge',
        'Dcw Editions',
        'De Majo',
        'De Padova',
        'Deknudt',
        'Delta Light',
        'Design House Stockholm',
        'Design Letters',
        'Designer Box',
        'Designheure',
        'Details - Pop Corn',
        'Diamantini & Domeniconi',
        'Diesel Living With Seletti',
        'Diesel With Foscarini',
        'Diesel With Moroso',
        'Diva',
        'Dix Heures Dix',
        'Doiy',
        'Domestic',
        'Dorelan',
        'Driade',
        'Pop Corn',
        'Drugeot',
        'Ego',
        'Elipson',
        'Emeco',
        'Emu',
        'Enea',
        'Enostudio',
        'Eoq',
        'Ercol',
        'Esé - Édition Sous Étiquette',
        'Essey',
        'Established & Sons',
        'Eumenes',
        'Eva Solo',
        'Extremis',
        'Fab Design',
        'Fabbian',
        'Fair Trade Original - Pop Corn',
        'Fast',
        'Fatboy',
        'Ferm Living',
        'Fermob',
        'Fermob Idoles',
        'Fiam',
        'Fjord Fiesta',
        'Flos',
        'Flux',
        'Fontana Arte',
        'Forestier',
        'Forge De Laguiole',
        'Foscarini',
        'Frama',
        'Franco Albini',
        'Frandsen',
        'Fritz Hansen',
        'Gallery S.Bensimon',
        'Gan',
        'Garden Glory',
        'Glas Italia',
        'Goods - Pop Corn',
        'Gras',
        'Gubi',
        'Gufram',
        'Guzzini',
        'Hartô',
        'Hay',
        'Heller',
        'Herman Miller',
        'Homka',
        'Horm',
        'Houe',
        'House Doctor',
        'Ibride',
        'Icf',
        'Ichiro',
        'Iittala',
        'Image Republic',
        'Incipit',
        'Ingo Maurer',
        'Innermost',
        'Innovation',
        'Internoitaliano',
        'Italesse',
        'Ixxi',
        'Jalo Helsinki',
        'Jardinico',
        'Jieldé',
        'Jonathan Adler',
        'Jorgensen, Erik',
        'Joseph Joseph',
        'Kartell',
        'Kast Van Een Huis',
        'Kdme - Pop Corn',
        'Kikkerland',
        'Kinnasand',
        'Kirigami Design',
        'Kitchenaid',
        'Knoll',
        'Koziol',
        'Kreafunk',
        'Kristalia',
        'Kubikoff',
        'Kundalini',
        'Kvadrat',
        'La Boîte Concept',
        'La Corbeille',
        'La Palma',
        'Label Edition',
        'Laorus',
        'Lapalma',
        'L\'atelier D\'exercices',
        'L\'atelier Du Vin',
        'Le Buisson',
        'Le Deun',
        'Leander',
        'Leçons De Choses',
        'Leff Amsterdam',
        'Leonardo',
        'Leonardo Bijoux',
        'Les Jardins Au Bout Du Monde',
        'Lexon',
        'Lightyears',
        'Linadura',
        'Lip',
        'Loris & Livia - Pop Corn',
        'Louis Poulsen',
        'Luceplan',
        'Luckies',
        'Lumen Center',
        'Luxy',
        'Made In Design Editions',
        'Made In Design Editions By Designfit',
        'Magis',
        'Magis Collection Me Too',
        'Maiori',
        'Maison De Vacances',
        'Maison Martin Margiela',
        'Maison Sarah Lavoine',
        'Malle W. Trousseau',
        'Mamagreen',
        'Mapoesie',
        'Marcel By',
        'Marimekko',
        'Mark\'s',
        'Marset',
        'Martinelli Luce',
        'Mathy By Bols',
        'Matière Grise',
        'Mattiazzi',
        'Mazzamiz',
        'Mdf Italia',
        'Meccano Home',
        'Megaman',
        'Memphis Milano',
        'Menu',
        'Michel Buffet',
        'Micuna',
        'Midj',
        'Mima',
        'Miras Editions',
        'Moaroom',
        'Mobles 114',
        'Modo Luce',
        'Mogg',
        'Molécule-R',
        'Moooi',
        'Morosini',
        'Moroso',
        'Moustache',
        'Muller',
        'Muuto',
        'My Your',
        'Mydrap',
        'Nanimarquina',
        'Napkiss',
        'Native Union',
        'Nemo',
        'Nicolas Vahé',
        'Nicolle',
        'Nomess',
        'Non Sans Raison',
        'Normann Copenhagen',
        'Norstone',
        'Northern Lighting',
        'Numero Unique',
        'Nuuna',
        'O Luce',
        'Objekto',
        'Œuf',
        'Offecct',
        'Ok Design Pour Sentou Edition',
        'Oluce',
        'Omy Design & Play',
        'Ondarreta',
        'Opinion Ciatti',
        'Ora Ïto Mobility',
        'O\'sun',
        'Oxyo',
        'Pa Design',
        'Parrot',
        'Pedrali',
        'Pension Für Produkte - Pop Corn',
        'Perigot',
        'Petite Friture',
        'Ph Collection',
        'Pic Vert Et Cie',
        'Pijama',
        'Plank',
        'Play With Dedon',
        'Plumen',
        'Pols Potten',
        'Pop Corn',
        'Pop Up Home',
        'Prandina',
        'Prostoria Ltd',
        'Pulse & Pulpe',
        'Punkt',
        'Quax',
        'Qui Est Paul ?',
        'Quinze & Milan',
        'Reflex',
        'Renova',
        'Rephorm',
        'Rescued - Pop Corn',
        'Rob Brandt - Pop Corn',
        'Roger Pradier',
        'Room Copenhagen',
        'Rotaliana',
        'Royal Botania',
        'Royal Vkb',
        'Rs Barcelona',
        'Sandrine Alouf Atmospheriste',
        'Schonbuch',
        'Schottlander',
        'Secto Design',
        'Seletti',
        'Sentou Edition',
        'Serafino Zani',
        'Serax',
        'Serge Lesage',
        'Serge Mouille',
        'Serralunga',
        'Sifas',
        'Sika Design',
        'Simple Human',
        'Sits',
        'Skargaarden',
        'Slide',
        'Smarin',
        'Snurk',
        'Softline',
        'Soldi Design',
        'Sonoro',
        'Sotto Luce',
        'Sovet',
        'Spécimen Editions',
        'Stamp Edition',
        'Stelton',
        'Stokke',
        'Storytiles',
        'String Furniture',
        'Structures',
        'Studio Ditte',
        'Suck Uk',
        'Supercraft',
        'Surplus Systems - Pop Corn',
        'Sywawa',
        'Tacchini',
        'Tangent',
        'Th Manufacture',
        'The Hansen Family',
        'Thelermont Hupton',
        'Tivoli Audio',
        'Tog',
        'Tolix',
        'Tom Dixon',
        'Tonelli',
        'Toulemonde Bochart',
        'Trimm Copenhagen',
        'Tsé-Tsé',
        'Tunto',
        'Umbra',
        'Universo Positivo',
        'Valsecchi 1918',
        'Vange',
        'Varier',
        'Variopinte',
        'Verpan',
        'Versus',
        'Vibia',
        'Viccarbe',
        'Vifa',
        'Viteo',
        'Vlaemynck',
        'Volteis',
        'Wästberg',
        'Withings',
        'Woud',
        'Wrong.London',
        'Xd Design',
        'Xl Boom',
        'Xo',
        'Y\'a Pas Le Feu Au Lac',
        'Zanotta',
        'Zee',
        'Zeitraum',
        'Zeus',
        'Zho - Pop Corn',
    ],
    'État' => [
        'Excellent',
        'Bon',
        'À restaurer',
    ]
];