<?php

namespace UserBundle\Repository;

use OrderBundle\Entity\Order;
use UserBundle\Entity\User;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Order $order
     * @param User $seller
     * @return null|object
     */
    public function findRatedSeller(Order $order)
    {

        return $this->findOneBy([
            'order'     => $order,
            'authorUser' => $order->getProduct()->getUser()
        ]);


    }

    /**
     * @param Order $order
     * @param User $buyer
     * @return null|object
     */
    public function findRatedBuyer(Order $order)
    {

        return $this->findOneBy([
            'order'     => $order,
            'authorUser' => $order->getUser()
        ]);

    }

}
