<?php

namespace UserBundle\Repository;

use OrderBundle\Entity\Order;
use UserBundle\Entity\User;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param Order $order
     * @param User $seller
     * @return null|object
     */
    public function findRatedSeller(Order $order, User $seller)
    {

        return $this->findOneBy([
            'order'     => $order,
            'ratedUser' => $seller
        ]);


    }

    /**
     * @param Order $order
     * @param User $buyer
     * @return null|object
     */
    public function findRatedBuyer(Order $order, User $buyer)
    {

        return $this->findOneBy([
            'order'     => $order,
            'ratedUser' => $buyer
        ]);

    }

}
