<?php

namespace UserBundle\Repository;

use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\VarDumper\Cloner\Data;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function count($statusName = null)
    {

        $query = $this->createQueryBuilder('u')
            ->select('count(u.id)');

        if ($statusName == 'afk') {

            $date = new \DateTime();

            $query->where('u.lastLogin < :date');
            $query->setParameter('date', $date->sub(new \DateInterval('P1M')));
        }

        if ($statusName == 'active') {

            $date = new \DateTime();

            $query->where('u.lastLogin > :date');
            $query->setParameter('date', $date->sub(new \DateInterval('P1M')));
        }


        return $query
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }

}
