<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    /**
     * @param null $id
     * @return QueryBuilder
     */
    public function getQueryByCategory($id = null)
    {
        $query = $this->createQueryBuilder("a")
            ->where('a.published = :published')
            ->addOrderBy('a.createdAt', 'DESC')
            ->setParameter('published', true);

        if ($id) {
            $query->andWhere('a.category = :category')
                ->setParameter('category', $id);
        }

        return $query;
    }

}
