<?php

namespace BlogBundle\Repository;

/**
 * BlogCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
