<?php

namespace OrderBundle\Repository;

use Doctrine\ORM\Query;
use UserBundle\Entity\User;

/**
 * OrderProposalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProposalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function findUserLimit(User $user)
    {
        $day = (new \DateTime())->format("Y-m-d");

        $builder = $this->createQueryBuilder('q')
            ->select('COUNT(q) total')
            ->where('q.user = :user')
            ->andWhere('q.createdAt LIKE :date')
            ->setParameters(['user' => $user, 'date' => $day."%"])
            ->getQuery()
            ->getResult(Query::HYDRATE_SINGLE_SCALAR);

        return $builder;
    }
}
