<?php

namespace OrderBundle\Repository;

/**
 * TransactionPayInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionPayRefundRepository extends \Doctrine\ORM\EntityRepository
{
}
