<?php

namespace OrderBundle\Repository;

/**
 * WeightRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeightRepository extends \Doctrine\ORM\EntityRepository
{
}
