parameters:
  notification:
      order_pending:
        message: "Vous avez une nouvelle commande concernant l'annonce #product_title#."
        route: 'user_account_sale'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'


      order_canceled:
        message: "Le vendeur a annulé la commande concernant l'annonce #product_title#. Vous allez être remboursé."
        route: 'user_account_purchase'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'


      order_accepted:
        message: "Le vendeur a accepté la commande concernant l'annonce #product_title#."
        route: 'user_account_purchase'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'


      order_disputed_open_buyer:
        message: "L'acheteur a ouvert un litige concernant l'annonce #product_title#."
        route: 'user_account_purchase'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'


      order_disputed_open_seller:
        message: "L'acheteur a ouvert un litige concernant l'annonce #product_title#."
        route: 'user_account_sale'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'


      order_disputed_closed_buyer:
        message: "Le litige concernant l'annonce #product_title# est terminé."
        route: 'user_account_purchase'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'

      order_disputed_closed_seller:
        message: "Le litige concernant l'annonce #product_title# est terminé."
        route: 'user_account_sale'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'

      order_done:
        message: "L'acheteur confirmé la bonne réception de sa commande concernant votre annonce #product_title#."
        route: 'user_account_sale'
        params: ['product_title', 'order_id']
        routeParams:
          id: 'order_id'

      order_done_wallet_transfer:
        message: "L'argent de la commande concernant l'annonce #product_title# est crédité sur votre porte-monnaie."
        route: 'user_account_wallet'
        params: ['product_title']

      order_proposal_new:
        message: "Une nouvelle offre concernant l'annonce #product_title# a soumise."
        route: "offer_validation"
        params: ['product_title', 'proposal_id']
        routeParams:
          id: 'proposal_id'

      order_proposal_change:
        message: "Votre offre concernant l'annonce #product_title# a été #change#"
        route: 'product_details'
        params: ['product_title', 'product_id', 'product_slug', 'change']
        routeParams :
          id : 'product_id'
          slug: 'product_slug'

      comment_new:
        message: "Vous avez reçu un nouveau commentaire sur l'annonce #product_title#"
        route: 'product_details'
        params: ['product_title', 'product_id', 'product_slug']
        routeParams :
          id : 'product_id'
          slug: 'product_slug'

      comment_reply:
        message: "Vous avez reçu une réponse à votre commentaire sur l'annonce #product_title#"
        route: 'product_details'
        params: ['product_title', 'product_id', 'product_slug']
        routeParams :
          id : 'product_id'
          slug: 'product_slug'



