services:
    user.registration_listener:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@mangopay_service', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    user.edit_listener:
        class: UserBundle\EventListener\EditListener
        arguments: ['@mangopay_service']
        tags:
            - { name: kernel.event_subscriber }
    user.notification:
        class: UserBundle\Service\NotificationService
        arguments: ['@doctrine.orm.entity_manager', '%notification%']