services:
    user.registration_listener:
        class: UserBundle\EventListener\RegistrationListener
        arguments: ['@mangopay_service', '@doctrine.orm.entity_manager', '@router']
        tags:
            - { name: kernel.event_subscriber }

    user.edit_listener:
        class: UserBundle\EventListener\EditListener
        arguments: ['@mangopay_service']
        tags:
            - { name: kernel.event_subscriber }
    user.notification:
        class: UserBundle\Service\NotificationService
        arguments: ['@doctrine.orm.entity_manager', '%notification%']

    fos_user.mailer.send:
        class: FOS\UserBundle\Mailer\Mailer
        arguments:
          - '@mailer'
          - '@router'
          - '@templating'
          - { confirmation.template: %fos_user.registration.confirmation.template%, resetting.template: %fos_user.resetting.email.template%, from_email: { confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email%}}