<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `noname`
//

// `noname`.`county`
return $county = array(
  array('id' => '1','name' => 'Ain ','code' => '01','slug' => 'ain'),
  array('id' => '2','name' => 'Aisne','code' => '02','slug' => 'aisne'),
  array('id' => '3','name' => 'Allier','code' => '03','slug' => 'allier'),
  array('id' => '4','name' => 'Alpes-de-Haute-Provence','code' => '04','slug' => 'alpes-de-haute-provence'),
  array('id' => '5','name' => 'Hautes-Alpes ','code' => '05','slug' => 'hautes-alpes'),
  array('id' => '6','name' => 'Alpes-Maritimes','code' => '06','slug' => 'alpes-maritimes'),
  array('id' => '7','name' => 'Ardèche ','code' => '07','slug' => 'ardeche'),
  array('id' => '8','name' => 'Ardennes','code' => '08','slug' => 'ardennes'),
  array('id' => '9','name' => 'Ariège','code' => '09','slug' => 'ariege'),
  array('id' => '10','name' => 'Aube','code' => '10','slug' => 'aube'),
  array('id' => '11','name' => 'Aude ','code' => '11','slug' => 'aude'),
  array('id' => '12','name' => 'Aveyron','code' => '12','slug' => 'aveyron'),
  array('id' => '13','name' => 'Bouches-du-Rhône','code' => '13','slug' => 'bouches-du-rhone'),
  array('id' => '14','name' => 'Calvados','code' => '14','slug' => 'calvados'),
  array('id' => '15','name' => 'Cantal','code' => '15','slug' => 'cantal'),
  array('id' => '16','name' => 'Charente','code' => '16','slug' => 'charente'),
  array('id' => '17','name' => 'Charente-Maritime','code' => '17','slug' => 'charente-maritime'),
  array('id' => '18','name' => 'Cher','code' => '18','slug' => 'cher'),
  array('id' => '19','name' => 'Corrèze','code' => '19','slug' => 'correze'),
  array('id' => '20','name' => 'Côte-d\'Or','code' => '21','slug' => 'cote-d-or'),
  array('id' => '21','name' => 'Côtes d\'Armor','code' => '22','slug' => 'cotes-d-armor'),
  array('id' => '22','name' => 'Creuse','code' => '23','slug' => 'creuse'),
  array('id' => '23','name' => 'Dordogne','code' => '24','slug' => 'dordogne'),
  array('id' => '24','name' => 'Doubs','code' => '25','slug' => 'doubs'),
  array('id' => '25','name' => 'Drôme','code' => '26','slug' => 'drome'),
  array('id' => '26','name' => 'Eure','code' => '27','slug' => 'eure'),
  array('id' => '27','name' => 'Eure-et-Loir','code' => '28','slug' => 'eure-et-loir'),
  array('id' => '28','name' => 'Finistère','code' => '29','slug' => 'finistere'),
  array('id' => '29','name' => 'Gard','code' => '30','slug' => 'gard'),
  array('id' => '30','name' => 'Haute-Garonne','code' => '31','slug' => 'haute-garonne'),
  array('id' => '31','name' => 'Gers','code' => '32','slug' => 'gers'),
  array('id' => '32','name' => 'Gironde','code' => '33','slug' => 'gironde'),
  array('id' => '33','name' => 'Hérault','code' => '34','slug' => 'herault'),
  array('id' => '34','name' => 'Ille-et-Vilaine','code' => '35','slug' => 'ille-et-vilaine'),
  array('id' => '35','name' => 'Indre','code' => '36','slug' => 'indre'),
  array('id' => '36','name' => 'Indre-et-Loire ','code' => '37','slug' => 'indre-et-loire'),
  array('id' => '37','name' => 'Isère','code' => '38','slug' => 'isere'),
  array('id' => '38','name' => 'Jura','code' => '39','slug' => 'jura'),
  array('id' => '39','name' => 'Landes','code' => '40','slug' => 'landes'),
  array('id' => '40','name' => 'Loir-et-Cher','code' => '41','slug' => 'loir-et-cher'),
  array('id' => '41','name' => 'Loire','code' => '42','slug' => 'loire'),
  array('id' => '42','name' => 'Haute-Loire','code' => '43','slug' => 'haute-loire'),
  array('id' => '43','name' => 'Loire-Atlantique','code' => '44','slug' => 'loire-atlantique'),
  array('id' => '44','name' => 'Loiret','code' => '45','slug' => 'loiret'),
  array('id' => '45','name' => 'Lot','code' => '46','slug' => 'lot'),
  array('id' => '46','name' => 'Lot-et-Garonne','code' => '47','slug' => 'lot-et-garonne'),
  array('id' => '47','name' => 'Lozère','code' => '48','slug' => 'lozere'),
  array('id' => '48','name' => 'Maine-et-Loire','code' => '49','slug' => 'maine-et-loire'),
  array('id' => '49','name' => 'Manche','code' => '50','slug' => 'manche'),
  array('id' => '50','name' => 'Marne','code' => '51','slug' => 'marne'),
  array('id' => '51','name' => 'Haute-Marne','code' => '52','slug' => 'haute-marne'),
  array('id' => '52','name' => 'Mayenne','code' => '53','slug' => 'mayenne'),
  array('id' => '53','name' => 'Meurthe-et-Moselle','code' => '54','slug' => 'meurthe-et-moselle'),
  array('id' => '54','name' => 'Meuse','code' => '55','slug' => 'meuse'),
  array('id' => '55','name' => 'Morbihan','code' => '56','slug' => 'morbihan'),
  array('id' => '56','name' => 'Moselle','code' => '57','slug' => 'moselle'),
  array('id' => '57','name' => 'Nièvre','code' => '58','slug' => 'nievre'),
  array('id' => '58','name' => 'Nord','code' => '59','slug' => 'nord'),
  array('id' => '59','name' => 'Oise','code' => '60','slug' => 'oise'),
  array('id' => '60','name' => 'Orne','code' => '61','slug' => 'orne'),
  array('id' => '61','name' => 'Pas-de-Calais','code' => '62','slug' => 'pas-de-calais'),
  array('id' => '62','name' => 'Puy-de-Dôme','code' => '63','slug' => 'puy-de-dome'),
  array('id' => '63','name' => 'Pyrénées-Atlantiques','code' => '64','slug' => 'pyrenees-atlantiques'),
  array('id' => '64','name' => 'Hautes-Pyrénées','code' => '65','slug' => 'hautes-pyrenees'),
  array('id' => '65','name' => 'Pyrénées-Orientales','code' => '66','slug' => 'pyrenees-orientales'),
  array('id' => '66','name' => 'Bas-Rhin','code' => '67','slug' => 'bas-rhin'),
  array('id' => '67','name' => 'Haut-Rhin','code' => '68','slug' => 'haut-rhin'),
  array('id' => '68','name' => 'Rhône','code' => '69','slug' => 'rhone'),
  array('id' => '69','name' => 'Haute-Saône','code' => '70','slug' => 'haute-saone'),
  array('id' => '70','name' => 'Saône-et-Loire','code' => '71','slug' => 'saone-et-loire'),
  array('id' => '71','name' => 'Sarthe','code' => '72','slug' => 'sarthe'),
  array('id' => '72','name' => 'Savoie','code' => '73','slug' => 'savoie'),
  array('id' => '73','name' => 'Haute-Savoie','code' => '74','slug' => 'haute-savoie'),
  array('id' => '74','name' => 'Paris','code' => '75','slug' => 'paris'),
  array('id' => '75','name' => 'Seine-Maritime','code' => '76','slug' => 'seine-maritime'),
  array('id' => '76','name' => 'Seine-et-Marne','code' => '77','slug' => 'seine-et-marne'),
  array('id' => '77','name' => 'Yvelines','code' => '78','slug' => 'yvelines'),
  array('id' => '78','name' => 'Deux-Sèvres','code' => '79','slug' => 'deux-sevres'),
  array('id' => '79','name' => 'Somme','code' => '80','slug' => 'somme'),
  array('id' => '80','name' => 'Tarn','code' => '81','slug' => 'tarn'),
  array('id' => '81','name' => 'Tarn-et-Garonne','code' => '82','slug' => 'tarn-et-garonne'),
  array('id' => '82','name' => 'Var','code' => '83','slug' => 'var'),
  array('id' => '83','name' => 'Vaucluse','code' => '84','slug' => 'vaucluse'),
  array('id' => '84','name' => 'Vendée','code' => '85','slug' => 'vendee'),
  array('id' => '85','name' => 'Vienne','code' => '86','slug' => 'vienne'),
  array('id' => '86','name' => 'Haute-Vienne','code' => '87','slug' => 'haute-vienne'),
  array('id' => '87','name' => 'Vosges','code' => '88','slug' => 'vosges'),
  array('id' => '88','name' => 'Yonne','code' => '89','slug' => 'yonne'),
  array('id' => '89','name' => 'Terr. de Belfort','code' => '90','slug' => 'terr-de-belfort'),
  array('id' => '90','name' => 'Essonne','code' => '91','slug' => 'essonne'),
  array('id' => '91','name' => 'Hauts-de-Seine','code' => '92','slug' => 'hauts-de-seine'),
  array('id' => '92','name' => 'Seine-St-Denis','code' => '93','slug' => 'seine-st-denis'),
  array('id' => '93','name' => 'Val-de-Marne','code' => '94','slug' => 'val-de-marne'),
  array('id' => '94','name' => 'Val-D\'Oise','code' => '95','slug' => 'val-d-oise'),
  array('id' => '95','name' => 'Corse-du-Sud','code' => '2A','slug' => 'corse-du-sud'),
  array('id' => '96','name' => 'Haute-Corse','code' => '2B','slug' => 'haute-corse'),
  array('id' => '97','name' => 'Guadeloupe','code' => '971','slug' => 'guadeloupe'),
  array('id' => '98','name' => 'Martinique','code' => '972','slug' => 'martinique'),
  array('id' => '99','name' => 'Guyane','code' => '973','slug' => 'guyane'),
  array('id' => '100','name' => 'La Réunion','code' => '974','slug' => 'la-reunion')
);
