<?php

namespace CommentBundle\Repository;

/**
 * ThreadCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
