services:
    my_admin_bundle.menu_listener:
        class: Admin2Bundle\EventListener\MenuItemListListener
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }