<?php

namespace LocationBundle\Repository;

use Doctrine\ORM\Query;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByZipcodeToArray($zipcode)
    {
        return $this->createQueryBuilder("q")
            ->setMaxResults(1)
            ->where("q.zipcode = :zipcode")
            ->setParameter("zipcode", $zipcode)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);

    }
}
