<?php

namespace ProductBundle\Repository;

/**
 * AttributeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
