<?php

namespace ProductBundle\Repository;

/**
 * AttributeDepositTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeDepositTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
