<?php

namespace ProductBundle\Repository;

/**
 * AttributeTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
