<?php

namespace ProductBundle\Repository;

/**
 * AttributeSearchTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributeSearchTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
