<?php

namespace ProductBundle\Repository;

/**
 * CollectionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollectionImageRepository extends \Doctrine\ORM\EntityRepository
{
}
