<?php

namespace ProductBundle\Repository;

/**
 * ReferentialValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentialValueRepository extends \Doctrine\ORM\EntityRepository
{
}
