<?php

namespace ProductBundle\Repository;

/**
 * ReferentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReferentialRepository extends \Doctrine\ORM\EntityRepository
{
}
