<?php

namespace ProductBundle\Repository;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findForUserProducts()
    {
        return $this->createQueryBuilder("q")
            ->where("q.name = :first")
            ->orWhere("q.name = :second")
            ->orWhere("q.name = :third")
            ->setParameters(['first' => "awaiting", 'second' => "published", 'third' => "refused"])
            ->getQuery()
            ->getResult();
    }
}
